<?php

namespace AppBundle\Repository;

/**
 * ExchangeProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
